Receptsamlingen.Mvc/Models/Partials/LoginModel.cs
namespace Receptsamlingen.Mvc.Models.Partials
{
    public class LoginModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

Receptsamlingen.Mvc/Models/Partials/QuickSearchModel.cs
namespace Receptsamlingen.Mvc.Models.Partials
{
	public class QuickSearchModel
	{
		public string Query { get; set; }
	}
}

Receptsamlingen.Mvc/Models/Partials/RandomModel.cs
namespace Receptsamlingen.Mvc.Models.Partials
{
	public class RandomModel
	{
	}
}

Receptsamlingen.Mvc/Models/Partials/ToplistModel.cs
using System.Collections.Generic;
using Ninject;
using Receptsamlingen.Mvc.Classes;
using Receptsamlingen.Repository;
using Receptsamlingen.Repository.Interfaces;

namespace Receptsamlingen.Mvc.Models.Partials
{
	public class ToplistModel
	{
		[Inject]
		public IRecipeRepository RecipeRepository { get; set; }

		public ToplistModel()
		{
			var kernel = new StandardKernel(new NinjectBindingModule());
			kernel.Inject(this);
		}

		private IList<Recipe> _source;
		public IList<Recipe> Source
		{
			get
			{
				return _source ?? (_source = RecipeRepository.GetToplist(SessionHandler.ForceReload));
			}
		}
	}
}

Receptsamlingen.Mvc/Controllers/LoginController.cs
using System.Web.Mvc;
using Ninject;
using Receptsamlingen.Mvc.Classes;
using Receptsamlingen.Mvc.Models.Partials;
using Receptsamlingen.Repository.Interfaces;

namespace Receptsamlingen.Mvc.Controllers
{
    public class LoginController : Controller
    {
        [Inject]
		public IUserRepository UserRepository { get; set; }

		public LoginController()
		{
			this.Inject();
		}

        public ActionResult DoLogin(LoginModel model)
        {
            if (!string.IsNullOrWhiteSpace(model.Username) && !string.IsNullOrWhiteSpace(model.Password))
            {
                var username = model.Username.Trim().StripHtml();
                var password = model.Password.Trim().StripHtml();
                var user = UserRepository.Get(username);
                var verifiedPassword = HashUtility.CheckPassword(password, user.Password);

                if (user != null && verifiedPassword)
                {
                    SessionHandler.User = user;
	                SessionHandler.IsAuthenticated = true;
					SessionHandler.FailedLogin = false;
                }
                else
                {
	                SessionHandler.IsAuthenticated = false;
					SessionHandler.FailedLogin = true;
                }
            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult DoLogout()
        {
            SessionHandler.Remove(Globals.UserSessionKeyString);
			SessionHandler.Remove(Globals.IsAuthenticatedSessionString);
            return RedirectToAction("Index", "Home");
        }
    }
}

Receptsamlingen.Mvc/Controllers/RandomController.cs
using System;
using System.Web.Mvc;
using Receptsamlingen.Mvc.Classes;

namespace Receptsamlingen.Mvc.Controllers
{
    public class RandomController : Controller
    {
        public ActionResult Randomize()
        {
			var idList = SessionHandler.RecipeIdList;
			var total = idList.Count;
			var randomNumber = new Random().Next(0, total - 1);
			var generatedRecipeId = idList[randomNumber];
			return RedirectToAction("Id", "Recipe",  new { id = generatedRecipeId });
        }
    }
}

Receptsamlingen.Mvc/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ninject;
using Receptsamlingen.Mvc.Classes;
using Receptsamlingen.Mvc.Models;
using Receptsamlingen.Repository.Interfaces;
using Receptsamlingen.Repository;

namespace Receptsamlingen.Mvc.Controllers
{
	public class SearchController : Controller
	{
		[Inject]
		public IRecipeRepository RecipeRepository { get; set; }

		public SearchController()
		{
            ViewBag.Title = "Sök";
            this.Inject();
		}

		public ActionResult Index()
		{
			var model = new SearchModel();
			model = GetModel(model);
			return View(model);
		}

		public ActionResult DoSearch(SearchModel model)
		{
			var category = model.SelectedCategory != null ? int.Parse(model.SelectedCategory) : 0;
			var dishType = model.SelectedDishType != null ? int.Parse(model.SelectedDishType) : 0;
			var specials = GetSelectedSpecials(model.PostedSpecials);
			model.SearchResult = RecipeRepository.Search(model.Query.StripHtml(), category, dishType, specials);
			model.SearchPerformed = true;
			model = GetModel(model);
			return View("Index", model);
		}

		private SearchModel GetModel(SearchModel model)
		{
			var allCategories = RecipeRepository.GetAllCategories();
			var allDishTypes = RecipeRepository.GetAllDishTypes();
			var allSpecials = RecipeRepository.GetAllSpecials();

			var categoryItems = new List<SelectListItem>
			{
				new SelectListItem { Text = "--- Välj ---", Value = "0" }
			};
			var dishTypeItems = new List<SelectListItem>
			{
				new SelectListItem { Text = "--- Välj ---", Value = "0" }
			};

			categoryItems.AddRange(allCategories.Select(category => new SelectListItem { Text = category.Name, Value = category.Id.ToString() }));
			dishTypeItems.AddRange(allDishTypes.Select(dishType => new SelectListItem { Text = dishType.Name, Value = dishType.Id.ToString() }));

			model.CategoryList = categoryItems;
			model.DishTypeList = dishTypeItems;
			model.SpecialList = allSpecials;
			model.SelectedSpecials = GetSelectedSpecials(model.PostedSpecials);
			return model;
		}

        private IList<Special> GetSelectedSpecials(PostedSpecials postedSpecials)
        {
            IList<Special> selectedSpecials = new List<Special>();
            var postedSpecialIds = new string[0];

            if (postedSpecials == null)
            {
                postedSpecials = new PostedSpecials();
            }

            if (postedSpecials.Ids != null && postedSpecials.Ids.Any())
            {
                postedSpecialIds = postedSpecials.Ids;
            }

            if (postedSpecialIds.Any())
            {
                selectedSpecials = RecipeRepository.GetAllSpecials().Where(x => postedSpecialIds.Any(s => x.Id.ToString().Equals(s))).ToList();
            }
            return selectedSpecials;
        }
    }
}

Receptsamlingen.Mvc/Views/Shared/Partials/Confirm.cshtml
<div id="dialog-confirm" title="Vill du radera receptet?">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Receptet raderas permanent.<br />Är du säker?</p>
</div>

Receptsamlingen.Mvc/Views/Shared/Partials/Login.cshtml
@using Receptsamlingen.Mvc.Classes
@model Receptsamlingen.Mvc.Models.Partials.LoginModel

<div class="box-wrapper">
	<div class="box-content">
		@if (SessionHandler.User == null && !SessionHandler.IsAuthenticated)
		{
			using (Html.BeginForm("DoLogin", "Login", FormMethod.Post))
			{
				<div class="row">
					<div class="col-md-12 padding-bottom-10">
						@Html.TextBoxFor(model => model.Username, new { @class = "form-control", placeholder = "Användarnamn" })
					</div>
				</div>
				<div class="row">
					<div class="col-md-12 padding-bottom-10">
						@Html.PasswordFor(model => model.Password, new { @class = "form-control", placeholder = "Lösenord" })
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<input type="submit" value="Logga in &raquo;" class="btn btn-warning width-100-percent" />
					</div>
				</div>
			}
			if (SessionHandler.FailedLogin)
			{
				<div class="row">
					<div class="col-md-12 padding-top-5 text-align-center">
						<label class="info-text login-error">@Globals.ErrorLogin</label>
					</div>
				</div>
			}
		}
		else
		{
			using (Html.BeginForm("DoLogout", "Login", FormMethod.Post))
			{
				<div class="row">
					<div class="col-md-12 padding-bottom-10">
						<label>
							Du är inloggad som
							@if (SessionHandler.IsAuthenticated && SessionHandler.User != null)
							{
								<span class="orange">@SessionHandler.User.Username</span>
							}
						</label>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<input type="submit" value="Logga ut &raquo;" class="btn btn-warning width-100-percent" />
					</div>
				</div>
			}
		}
	</div>
</div>

Receptsamlingen.Mvc/Views/Shared/Partials/QuickSearch.cshtml
@model Receptsamlingen.Mvc.Models.Partials.QuickSearchModel

<div class="box-wrapper">
	<div class="box-content">
		@using (Html.BeginForm("DoSearch", "Search", FormMethod.Post))
		{
			<div class="row">
				<div class="col-md-12 padding-bottom-10">
					@Html.TextBoxFor(model => model.Query, new { @class = "form-control", placeholder = "Sök..." })
				</div>
            </div>
            <div class="row">
				<div class="col-md-12">
					<input type="submit" value="Sök &raquo;" class="btn btn-warning width-100-percent" />
				</div>
			</div>
		}
	</div>
</div>

Receptsamlingen.Mvc/Views/Shared/Partials/Random.cshtml
@model Receptsamlingen.Mvc.Models.Partials.RandomModel

<div class="box-wrapper">
	<div class="box-content">
		<div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("Randomize", "Random", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <input type="submit" value="Slumpa fram ett recept &raquo;" class="btn btn-warning width-100-percent" />
                }
            </div>
		</div>
	</div>
</div>

Receptsamlingen.Mvc/Views/Shared/Partials/Toplist.cshtml
@model Receptsamlingen.Mvc.Models.Partials.ToplistModel

<div class="box-wrapper">
	<div class="box-content">
		<div class="row">
			<div class="col-md-12">
				<h3>= = = Topp 5 = = =</h3>
				@if (Model.Source != null)
				{
					<ul>
						@foreach (var r in Model.Source)
						{
                        <li>
                            &raquo;&nbsp;@Html.ActionLink(r.Name, "Id", "Recipe", new { id = r.Id }, null)
                            <br />
                        </li>
						}
					</ul>
				}
				else
				{
					<p>Det finns inga röster än...</p>
				}
			</div>
		</div>
	</div>
</div>