Receptsamlingen.Mvc/Controllers/ApplyController.cs
using System.Web.Mvc;
using Ninject;
using Receptsamlingen.Mvc.Classes;
using Receptsamlingen.Mvc.Models;
using Receptsamlingen.Repository.Interfaces;
using Logger;

namespace Receptsamlingen.Mvc.Controllers
{
    public class ApplyController : Controller
    {
        [Inject]
        public IRecipeRepository RecipeRepository { get; set; }

        [Inject]
        public IUserRepository UserRepository { get; set; }

        public ApplyController()
        {
            ViewBag.Title = "Skapa konto";
            this.Inject();
        }

        public ActionResult Index()
        {
            return View(new ApplyModel());
        }

        public ActionResult DoApply(ApplyModel model)
        {
            if (model.Human && model.Alien)
            {
                ViewBag.Response = Globals.ErrorOnlyOneBoxCanBeSelected;
                ViewBag.Result = false.ToString();
            }
            else if (model.Alien && !model.Human)
            {
                ViewBag.Response = Globals.ErrorNoAccountGranted;
                ViewBag.Result = false.ToString();
            }
            else if (!model.Alien && model.Human)
            {
                if (model.Email != null && model.FullName != null && model.Username != null)
                {
                    var emailAddress = model.Email.Trim().StripHtml();
                    var fullName = model.FullName.Trim().StripHtml();
                    var userName = model.Username.Trim().StripHtml();
                    if (!Helper.ValidateEmail(emailAddress))
                    {
                        ViewBag.Response = Globals.ErrorInvalidEmail;
                        ViewBag.Result = false.ToString();
                    }
                    else
                    {
                        var hashedPassword = HashUtility.HashPassword(model.Password);
                        var userCreated = UserRepository.Create(userName, hashedPassword, fullName, emailAddress);
                        if (userCreated)
                        {
                            Helper.SendMail(emailAddress, fullName, userName, model.Password);
                            ViewBag.Response = Globals.InfoApplyApproved;
                            ViewBag.Result = true.ToString();
                            LogHandler.Log(nameof(ApplyController), LogType.Info, string.Format("Account created \t email: {0} fullname: {1} username: {2}", emailAddress, fullName, userName));
                        }
                        else
                        {
                            ViewBag.Response = Globals.ErrorCreatingAccount;
                            ViewBag.Result = false.ToString();
                        }
                    }
                }
                else
                {
                    ViewBag.Response = Globals.ErrorMustGiveInfo;
                    ViewBag.Result = false.ToString();
                }
            }
            else
            {
                ViewBag.Response = Globals.ErrorMustChooseBox;
                ViewBag.Result = false.ToString();
            }
            return View("Index");
        }
    }
}

Receptsamlingen.Mvc/Controllers/ListController.cs
using System.Web.Mvc;
using Ninject;
using Receptsamlingen.Mvc.Classes;
using Receptsamlingen.Mvc.Models;
using Receptsamlingen.Repository.Interfaces;

namespace Receptsamlingen.Mvc.Controllers
{
    public class ListController : Controller
    {
	    [Inject]
		public IRecipeRepository RecipeRepository { get; set; }

		public ListController()
		{
            ViewBag.Title = "Alla recept";
            this.Inject();
		}

		public ActionResult Index()
		{
			var recipes = RecipeRepository.GetAll();

			var model = new ListModel
				{
					Recipes = recipes
				};

			return View(model);
        }
    }
}

Receptsamlingen.Mvc/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ninject;
using Receptsamlingen.Mvc.Classes;
using Receptsamlingen.Mvc.Models;
using Receptsamlingen.Repository;
using Receptsamlingen.Repository.Interfaces;
using System.Web;
using Logger;

namespace Receptsamlingen.Mvc.Controllers
{
    public class RecipeController : Controller
    {
        [Inject]
        public IRecipeRepository RecipeRepository { get; set; }
        [Inject]
        public IRatingRepository RatingRepository { get; set; }

        public RecipeController()
        {
            this.Inject();
        }

        public ActionResult Add()
        {
            ViewBag.Title = "Lägg till recept";
            var model = Load();
            SessionHandler.CurrentGuid = null;
            SessionHandler.CurrentId = null;
            return View("Manage", model);
        }

        public ActionResult Id(int id)
        {
            var model = Load(id);
            ViewBag.Title = model.Recipe.Name;
            return View("Detail", model);
        }

        public ActionResult Edit(int id)
        {
            var model = Load(id);
            ViewBag.Title = model.Recipe.Name;
            return View("Manage", model);
        }

        public ActionResult Save(RecipeModel model)
        {
            // If these seesions are null then it´s a new recipe to save
            if (SessionHandler.CurrentGuid == null && SessionHandler.CurrentId == null)
            {
                model.Recipe.Guid = Guid.NewGuid().ToString();
            }
            else
            {
                model.Recipe.Guid = SessionHandler.CurrentGuid;
                model.Recipe.Id = Convert.ToInt32(SessionHandler.CurrentId);
            }

            model.Recipe.Name.HtmlEncode();
            model.Recipe.Description.HtmlEncode();
            model.Recipe.Ingredients.HtmlEncode();
            model.Recipe.CategoryId = Convert.ToInt32(model.SelectedCategory);
            model.Recipe.DishTypeId = Convert.ToInt32(model.SelectedDishType);
            model.Recipe.Portions = Convert.ToInt32(model.SelectedPortions);

            var specials = GetSelectedSpecials(model.PostedSpecials);

            var result = RecipeRepository.Save(model.Recipe);
            if (result)
            {
                // Delete any specials saved to the recipe first
                var deleted = RecipeRepository.DeleteSpecials(model.Recipe.Guid);

                // Then save the new specials added to the recipe
                foreach (var special in specials)
                {
                    var saved = RecipeRepository.SaveSpecial(model.Recipe.Guid, special.Id);
                }

                if (model.Recipe.Id == 0) // This means that the recipe is a new one and we need to fetch the id for further use
                {
                    model.Recipe.Id = RecipeRepository.GetByGuid(model.Recipe.Guid).Id;
                }
                model.RecipeSaved = true;
                ViewBag.Response = Globals.InfoRecipeSaved;
                SessionHandler.CurrentGuid = model.Recipe.Guid;
                SessionHandler.CurrentId = model.Recipe.Id.ToString();
                SessionHandler.ForceReload = true;
            }
            else
            {
                model.RecipeSaved = false;
                ViewBag.Response = Globals.ErrorSavingRecipe;
            }

            ViewBag.Title = model.Recipe.Name;
            return View("Detail", model);
        }

        public ActionResult Vote(RecipeModel model)
        {
            var ratingSaved = false;
            if (RatingRepository.UserHasVoted(SessionHandler.User.Username, SessionHandler.CurrentGuid))
            {
                ViewBag.Response = Globals.ErrorUserHasVoted;
            }
            else
            {
                var voteSuccess = RatingRepository.Save(SessionHandler.CurrentGuid, SessionHandler.User.Username, Convert.ToInt32(model.UserRating));
                if (voteSuccess)
                {
                    ratingSaved = true;
                    ViewBag.Response = Globals.InfoVoteSaved;
                }
                else
                {
                    ViewBag.Response = Globals.ErrorSavingVote;
                }
            }
            model = Load(Convert.ToInt32(SessionHandler.CurrentId));
            model.RatingSaved = ratingSaved;
            return View("Detail", model);
        }

        public ActionResult Delete(int id)
        {
            var recipe = RecipeRepository.GetById(id);
            RecipeRepository.DeleteSpecials(recipe.Guid);
            RecipeRepository.Delete(recipe.Guid);
            RecipeRepository.DeleteVotes(recipe.Guid);
            ViewBag.Response = Globals.InfoRecipeDeleted;
            SessionHandler.ForceReload = true;
            return View("Response");
        }

        private RecipeModel Load(int id = 0)
        {
            var model = GetModel();

            if (id != 0)
            {
                var recipe = RecipeRepository.GetById(id);
                if (recipe != null)
                {
                    var category = RecipeRepository.GetCategoryById(recipe.CategoryId).HtmlDecode();
                    var specials = RecipeRepository.GetSpecialsForRecipe(recipe.Guid);
                    var selectedSpecials = (from item in specials
                                            from special in model.AllSpecials
                                            where item.SpecialId == special.Id
                                            select special).ToList();
                    var selectedSpecialsAsString = (from item in specials
                                                    from special in model.AllSpecials
                                                    where item.SpecialId == special.Id
                                                    select special).Aggregate(string.Empty, (current, special) => current + (special.Name.ToLower() + ", "));
                    var dishType = string.Empty;
                    var avgRating = RatingRepository.GetAvarage(recipe.Guid);
                    if (recipe.DishTypeId.HasValue)
                    {
                        dishType = RecipeRepository.GetDishTypeById(recipe.DishTypeId.Value);
                    }

                    if (selectedSpecialsAsString.EndsWith(", "))
                    {
                        selectedSpecialsAsString = selectedSpecialsAsString.TrimEnd(',', ' ');
                    }

                    model.Recipe = recipe;
                    model.Recipe.Name.HtmlDecode();
                    model.Recipe.Ingredients.HtmlDecode();
                    model.Recipe.Description.HtmlDecode();
                    model.Category = category;
                    model.DishType = dishType;
                    model.AvarageRating = avgRating;
                    model.Specials = selectedSpecialsAsString;
                    model.SelectedSpecials = selectedSpecials;
                    SessionHandler.CurrentGuid = model.Recipe.Guid;
                    SessionHandler.CurrentId = model.Recipe.Id.ToString();
                }
                else
                {
                    LogHandler.Log(nameof(RecipeController), LogType.Info, string.Format("Recipe with id: {0} could not be found", id));
                    throw new HttpException(404, "Not found");
                }
            }
            return model;
        }

        private RecipeModel GetModel()
        {
            var model = new RecipeModel();
            var allCategories = RecipeRepository.GetAllCategories();
            var allDishTypes = RecipeRepository.GetAllDishTypes();
            var allSpecials = RecipeRepository.GetAllSpecials();

            var categoryItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "--- Välj ---", Value = "0"}
            };
            var dishTypeItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "--- Välj ---", Value = "0"}
            };
            var portionItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "--- Välj ---", Value = "0"},
                new SelectListItem {Text = "1", Value = "1"},
                new SelectListItem {Text = "2", Value = "2"},
                new SelectListItem {Text = "3", Value = "3"},
                new SelectListItem {Text = "4", Value = "4"},
                new SelectListItem {Text = "5", Value = "5"},
                new SelectListItem {Text = "6", Value = "6"},
                new SelectListItem {Text = "7", Value = "7"},
                new SelectListItem {Text = "8", Value = "8"},
            };

            categoryItems.AddRange(allCategories.Select(category => new SelectListItem { Text = category.Name, Value = category.Id.ToString() }));
            dishTypeItems.AddRange(allDishTypes.Select(dishType => new SelectListItem { Text = dishType.Name, Value = dishType.Id.ToString() }));

            model.Recipe = new Recipe();
            model.AllCategories = categoryItems;
            model.AllDishTypes = dishTypeItems;
            model.Portions = portionItems;
            model.AllSpecials = allSpecials;
            return model;
        }

        private IList<Special> GetSelectedSpecials(PostedSpecials postedSpecials)
        {
            IList<Special> selectedSpecials = new List<Special>();
            var postedSpecialIds = new string[0];

            if (postedSpecials == null)
            {
                postedSpecials = new PostedSpecials();
            }

            if (postedSpecials.Ids != null && postedSpecials.Ids.Any())
            {
                postedSpecialIds = postedSpecials.Ids;
            }

            if (postedSpecialIds.Any())
            {

Receptsamlingen.Mvc/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ninject;
using Receptsamlingen.Mvc.Classes;
using Receptsamlingen.Mvc.Models;
using Receptsamlingen.Repository.Interfaces;
using Receptsamlingen.Repository;

namespace Receptsamlingen.Mvc.Controllers
{
	public class SearchController : Controller
	{
		[Inject]
		public IRecipeRepository RecipeRepository { get; set; }

		public SearchController()
		{
            ViewBag.Title = "Sök";
            this.Inject();
		}

		public ActionResult Index()
		{
			var model = new SearchModel();
			model = GetModel(model);
			return View(model);
		}

		public ActionResult DoSearch(SearchModel model)
		{
			var category = model.SelectedCategory != null ? int.Parse(model.SelectedCategory) : 0;
			var dishType = model.SelectedDishType != null ? int.Parse(model.SelectedDishType) : 0;
			var specials = GetSelectedSpecials(model.PostedSpecials);
			model.SearchResult = RecipeRepository.Search(model.Query.StripHtml(), category, dishType, specials);
			model.SearchPerformed = true;
			model = GetModel(model);
			return View("Index", model);
		}

		private SearchModel GetModel(SearchModel model)
		{
			var allCategories = RecipeRepository.GetAllCategories();
			var allDishTypes = RecipeRepository.GetAllDishTypes();
			var allSpecials = RecipeRepository.GetAllSpecials();

			var categoryItems = new List<SelectListItem>
			{
				new SelectListItem { Text = "--- Välj ---", Value = "0" }
			};
			var dishTypeItems = new List<SelectListItem>
			{
				new SelectListItem { Text = "--- Välj ---", Value = "0" }
			};

			categoryItems.AddRange(allCategories.Select(category => new SelectListItem { Text = category.Name, Value = category.Id.ToString() }));
			dishTypeItems.AddRange(allDishTypes.Select(dishType => new SelectListItem { Text = dishType.Name, Value = dishType.Id.ToString() }));

			model.CategoryList = categoryItems;
			model.DishTypeList = dishTypeItems;
			model.SpecialList = allSpecials;
			model.SelectedSpecials = GetSelectedSpecials(model.PostedSpecials);
			return model;
		}

        private IList<Special> GetSelectedSpecials(PostedSpecials postedSpecials)
        {
            IList<Special> selectedSpecials = new List<Special>();
            var postedSpecialIds = new string[0];

            if (postedSpecials == null)
            {
                postedSpecials = new PostedSpecials();
            }

            if (postedSpecials.Ids != null && postedSpecials.Ids.Any())
            {
                postedSpecialIds = postedSpecials.Ids;
            }

            if (postedSpecialIds.Any())
            {
                selectedSpecials = RecipeRepository.GetAllSpecials().Where(x => postedSpecialIds.Any(s => x.Id.ToString().Equals(s))).ToList();
            }
            return selectedSpecials;
        }
    }
}

Receptsamlingen.Mvc/Views/Shared/SiteLayout.cshtml
@using Receptsamlingen.Mvc.Models.Partials

<!DOCTYPE html>
<html>
<head>
	<meta name="robots" content="noindex,nofollow" />
	<meta http-equiv="content-type" content="charset=utf-8" />
	<meta name="HandheldFriendly" content="true" />
	<meta name="apple-mobile-web-app-title" content="Receptsamlingen" />
	<meta name="viewport" content="width=device-width.1, initial-scale=1.0, minimum-scale=1.0, user-scalable=0" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<title>@ViewBag.Title - Receptsamlingen</title>
	<link href="~/Content/Styles/normalize.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/Styles/bootstrap.min.css" rel="stylesheet" />
	<link href="~/Content/Styles/bootstrap-theme.min.css" rel="stylesheet" />
	<link href="~/Content/Styles/jquery-ui.min.css" rel="stylesheet" />
	<link href="~/Content/Styles/jquery-ui.structure.min.css" rel="stylesheet" />
	<link href="~/Content/Styles/jquery-ui.theme.min.css" rel="stylesheet" />
	<link href="~/Content/Styles/style.css" rel="stylesheet" type="text/css" />
	<link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/favicon.ico" />
	<script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"dffe282f-5a9e-479f-988f-625f24101bf5"
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
	</script>
	<script src="~/Content/Scripts/external/jquery.js"></script>
	<script src="~/Content/Scripts/bootstrap.min.js"></script>
	<script src="~/Content/Scripts/jquery-ui.min.js"></script>
	<script src="~/Content/Scripts/jquery.raty.min.js" type="text/javascript"></script>
	<script src="~/Content/Scripts/rating-handler.js" type="text/javascript"></script>
	<script src="~/Content/Scripts/dialog-handler.js" type="text/javascript"></script>
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<div class="container">
		<header class="row">
			<div class="col-md-12">
				<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
					<div class="container">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<a class="navbar-brand" href="/">
								<img alt="Brand" src="~/Content/Images/brand.png">
							</a>
						</div>
						<div id="navbar" class="navbar-collapse collapse">
							<ul class="nav navbar-nav">
								<li role="presentation">
									@Html.ActionLink("Lägg in recept", "Add", "Recipe")
								</li>
								<li role="presentation">
									@Html.ActionLink("Alla recept", "Index", "List")
								</li>
								<li role="presentation">
									@Html.ActionLink("Sök", "Index", "Search")
								</li>
								<li role="presentation">
									@Html.ActionLink("Skaffa konto", "Index", "Apply")
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</div>
		</header>
		<div class="wrapper row">
			<div class="col-md-9">
				@RenderBody()
			</div>
			<div class="col-md-3">
                <div class="row">
                    <div class="col-md-12">
                        @Html.Partial("~/Views/Shared/Partials/QuickSearch.cshtml", new QuickSearchModel())
                    </div>
                </div>
				<div class="row">
					<div class="col-md-12">
						@Html.Partial("~/Views/Shared/Partials/Login.cshtml", new LoginModel())
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						@Html.Partial("~/Views/Shared/Partials/Toplist.cshtml", new ToplistModel())
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						@Html.Partial("~/Views/Shared/Partials/Random.cshtml", new RandomModel())
					</div>
				</div>				
			</div>
		</div>
	</div>
</body>
</html>